### ISSUE TITLE
Changing the order of globbing imports

### ISSUE THREAD

**Issue by virajsoni** [DennisBecker/grunt-sass-globbing#15]
Hello @DennisBecker,

Thanks for the plugin. It is a real time saver. 

I've added it to my my grunt task and it is working all smoothly. Only problem is I have folders inside the globbing folder and a main .scss file inside the globbing folder which I need to call first. 
It could be better explained with this diagram

<pre>
GLOBBING FOLDER/
|
|-- folder1/              
|   |-- scss/
|		|-- *.scss
|		...
|-- folder2        
|   |-- scss
|		|-- *.scss
|		
|-- folder3/              
|   |-- scss/
|		|-- *.scss
|		...
|-- folder4/              
|   |-- scss/
|		|-- *.scss
|		
|-- main.scss
</pre>

I need the main.scss file to be called before any other .scss file is imported. Is this possible?

**Comment by DennisBecker** [comment]
The bad thing of globbing is, that you should accept that the ordering isn't guaranteed.

I think this could break a lot of projects if I change the order because I believe not everyone knows that ordering is not fix. At the moment, this plugin relies on the globbing mechanism of Grunt.

At the moment I would not want to change this behaviour or add an optional config switch for this until there were more requests for this feature.


You could work around this by creating @import map files for every folder and import these in your main.scss file.

**Comment by virajsoni** [comment]
Maybe yes, it can break a lot of projects.
Well then, I'll surely try a work around with @import map files.
BTW thanks for such a quick reply.

Cheers.
