### ISSUE TITLE
Use globbing without grunt

### ISSUE THREAD

**Issue by damnhipster** [DennisBecker/grunt-sass-globbing#25]
I'm trying to glob a directory without using Grunt (it's not a part of the project).

Looking through the [sass_globbing.js](https://github.com/DennisBecker/grunt-sass-globbing/blob/master/tasks/sass_globbing.js), it looks possible to separate the globbing logic from the Grunt task.

It would make it easier to install the package but import the globbing logic to use it without Grunt, if anyone wanted to.

What does everyone think?

**Comment by DennisBecker** [comment]
You can use https://www.npmjs.com/package/glob which also grunt uses as dependent package.

**Comment by damnhipster** [comment]
I would have to set up the import statements again if I use glob only. I was hoping sass_globbing.js could be imported/required without having to use the grunt interface.

**Comment by DennisBecker** [comment]
Hey @damnhipster - I have released a first version of the map creation logic as an npm package - you can find it at https://www.npmjs.com/package/sass-globbing - it is declared as alpha version because I have build it today und just released it.

Build details can be found at https://travis-ci.org/DennisBecker/sass-globbing
